/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClientActions: typeof import('./components/client-actions.vue')['default']
    ClientDomains: typeof import('./components/client-domains.vue')['default']
    ClientInfo: typeof import('./components/client-info.vue')['default']
    ClientList: typeof import('./components/client-list.vue')['default']
    ClientMenu: typeof import('./components/client-menu.vue')['default']
    DomainActions: typeof import('./components/domain-actions.vue')['default']
    DomainClients: typeof import('./components/domain-clients.vue')['default']
    DomainInfo: typeof import('./components/domain-info.vue')['default']
    DomainList: typeof import('./components/domain-list.vue')['default']
    DomainMenu: typeof import('./components/domain-menu.vue')['default']
    QueryCountLine: typeof import('./components/query-count-line.vue')['default']
    RiskRating: typeof import('./components/risk-rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyncLog: typeof import('./components/sync-log.vue')['default']
  }
}
