/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/clients': RouteRecordInfo<'/clients', '/clients', Record<never, never>, Record<never, never>>,
    '/clients-view': RouteRecordInfo<'/clients-view', '/clients-view', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/domains': RouteRecordInfo<'/domains', '/domains', Record<never, never>, Record<never, never>>,
    '/domains-view': RouteRecordInfo<'/domains-view', '/domains-view', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/clients.vue': {
      routes: '/clients'
      views: never
    }
    'src/pages/clients-view.vue': {
      routes: '/clients-view'
      views: never
    }
    'src/pages/dashboard.vue': {
      routes: '/dashboard'
      views: never
    }
    'src/pages/domains.vue': {
      routes: '/domains'
      views: never
    }
    'src/pages/domains-view.vue': {
      routes: '/domains-view'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
